# Generated by Django 6.0.1 on 2026-04-03 21:51

import accounts.models
import cloudinary_storage.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='audio_file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='publications/', validators=[accounts.models.validate_audio_size]),
        ),
        migrations.AlterField(
            model_name='publication',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='publications/covers/', validators=[accounts.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='tracks/', validators=[accounts.models.validate_audio_size]),
        ),
        migrations.AlterField(
            model_name='track',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/headers/', validators=[accounts.models.validate_header_size]),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/avatars/', validators=[accounts.models.validate_image_size]),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('like_track', 'Liked your track'), ('like_publication', 'Liked your publication'), ('follow', 'Followed you'), ('comment', 'Commented on your song'), ('repost', 'Reposted your song')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.publication')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.track')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
