# Generated by Django 6.0.1 on 2026-03-24 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_project_publication'),
        ('accounts', '0012_follow'),
    ]

    operations = [
    ]
