# Generated by Django 6.0.3 on 2026-04-05 23:19

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_publication_audio_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='audio_file',
            field=models.FileField(upload_to='publications/', validators=[accounts.models.validate_audio_size]),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(upload_to='tracks/', validators=[accounts.models.validate_audio_size]),
        ),
        migrations.CreateModel(
            name='ContentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.publication')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('publication__isnull', True), ('track__isnull', False)), models.Q(('publication__isnull', False), ('track__isnull', True)), _connector='OR'), name='contentcomment_exactly_one_target')],
            },
        ),
    ]
