# Generated by Django 6.0.3 on 2026-04-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_contentcomment_parent_body_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like_track', 'Liked your track'), ('like_publication', 'Liked your publication'), ('follow', 'Followed you'), ('comment', 'Commented on your song'), ('comment_reply', 'Replied to your comment'), ('repost', 'Reposted your song')], max_length=20),
        ),
    ]
