# Generated by Django 6.0.1 on 2026-04-06 04:35

import accounts.models
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_track_repost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like_track', 'Liked your track'), ('like_publication', 'Liked your publication'), ('follow', 'Followed you'), ('comment', 'Commented on your song'), ('comment_reply', 'Replied to your comment'), ('repost', 'Reposted your song'), ('mention', 'Mentioned you in a comment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='publication',
            name='audio_file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='publications/', validators=[accounts.models.validate_audio_size]),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='tracks/', validators=[accounts.models.validate_audio_size]),
        ),
    ]
