# Generated by Django 6.0.1 on 2026-04-09 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_track_price_purchase'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='publication',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='purchase',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='accounts.publication'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like_track', 'Liked your track'), ('like_publication', 'Liked your publication'), ('follow', 'Followed you'), ('comment', 'Commented on your song'), ('comment_reply', 'Replied to your comment'), ('repost', 'Reposted your song'), ('mention', 'Mentioned you in a comment'), ('purchase', 'Purchased your track')], max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='accounts.track'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(condition=models.Q(('track__isnull', False)), fields=('user', 'track'), name='unique_user_track_purchase'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(condition=models.Q(('publication__isnull', False)), fields=('user', 'publication'), name='unique_user_publication_purchase'),
        ),
    ]
