# Generated by Django 6.0.1 on 2026-04-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_marketplace_publication_price_purchase_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
    ]
